// apps/nextjs-standard-example/components/transactionFlow/Sponsor.tsx
import {
  AccountAddress,
  AccountAuthenticator,
  AnyRawTransaction,
} from "@aptos-labs/ts-sdk";
import { useWallet } from "@aptos-labs/wallet-adapter-react";
import { useState, useEffect } from "react";
import { aptosClient } from "../../utils";
import { useAlert } from "../AlertProvider";
import Button from "../Button";
import Col from "../Col";
import Row from "../Row";
export const APTOS_COIN = "0x1::aptos_coin::AptosCoin";
type SponsorTransactionProps = {
  isSendableNetwork: (connected: boolean, network?: string) => boolean;
};

export default function SponsorTransaction({
  isSendableNetwork,
}: SponsorTransactionProps) {
  const { connected, account, network, signTransaction, submitTransaction } =
    useWallet();
  const [transactionToSubmit, setTransactionToSubmit] =
    useState<AnyRawTransaction | null>(null);
  const { setSuccessAlertHash } = useAlert();

  const [senderAuthenticator, setSenderAuthenticator] =
    useState<AccountAuthenticator>();
  const [feepayerAuthenticator, setFeepayerAuthenticator] =
    useState<AccountAuthenticator>();
  const [feepayerAddress, setFeepayerAddress] = useState<AccountAddress>();

  let sendable = isSendableNetwork(connected, network?.name);

  useEffect(() => {
    if (!sendable) return;
    if (!account) return;
    if (!network) return;

    // Generate a raw transaction using the SDK
    const generate = async (): Promise<AnyRawTransaction> => {
      const transactionToSign = await aptosClient(
        network?.name.toLowerCase()
      ).transaction.build.simple({
        sender: account.address.toString(),
        withFeePayer: true,
        data: {
          function: "0x1::coin::transfer",
          typeArguments: [APTOS_COIN],
          functionArguments: [account.address.toString(), 1], // 1 is in Octas
        },
      });
      return transactionToSign;
    };

    // Fund current connected account to create it on chain
    const fundCurrentAccount = async () => {
      await aptosClient(network.name.toLowerCase()).fundAccount({
        accountAddress: account.address.toString(),
        amount: 100_000_000,
      });
    };

    // We fund the current connected account to create it on chain
    // Then we generate the transaction with the current connected account
    // as the sender
    fundCurrentAccount().then(() => {
      generate().then((transactionToSign) =>
        setTransactionToSubmit(transactionToSign)
      );
    });
  }, [network, account, sendable]);

  const onSignTransaction = async (asSponsor?: boolean) => {
    if (!transactionToSubmit) {
      throw new Error("No Transaction to sign");
    }
    try {
      const authenticator = await signTransaction(
        transactionToSubmit,
        asSponsor
      );
      if (asSponsor) {
        setFeepayerAuthenticator(authenticator);
        setFeepayerAddress(AccountAddress.from(account!.address.toString()));
      } else {
        setSenderAuthenticator(authenticator);
      }
    } catch (error) {
      console.error(error);
    }
  };

  const onSubmitTransaction = async () => {
    if (!transactionToSubmit) {
      throw new Error("No Transaction to sign");
    }
    if (!senderAuthenticator) {
      throw new Error("No senderAuthenticator");
    }
    if (!feepayerAuthenticator) {
      throw new Error("No feepayerAuthenticator");
    }
    transactionToSubmit.feePayerAddress = feepayerAddress;
    try {
      const response = await submitTransaction({
        transaction: transactionToSubmit,
        senderAuthenticator: senderAuthenticator,
        feePayerAuthenticator: feepayerAuthenticator,
      });
      setSuccessAlertHash(response.hash, network?.name);
    } catch (error) {
      console.error(error);
    }
  };

  return (
    <Row>
      <Col title={true} border={true}>
        <h3>Sponsor Transaction Flow</h3>
      </Col>
      <Col border={true}>
        <Button
          color={"blue"}
          onClick={() => onSignTransaction(false)}
          disabled={!sendable || !transactionToSubmit}
          message={"Sign as Sender"}
        />
        <Button
          color={"blue"}
          onClick={() => onSignTransaction(true)}
          disabled={!sendable || !senderAuthenticator}
          message={"Sign as Sponsor"}
        />
        <Button
          color={"blue"}
          onClick={onSubmitTransaction}
          disabled={!sendable || !feepayerAuthenticator}
          message={"Submit transaction"}
        />
      </Col>
    </Row>
  );
}

// apps/nuxt-example/components/TransactonFlows/Sponsor.vue
<script setup lang="ts">
import { ref, computed, h } from "vue";
import { aptosClient, isSendableNetwork } from "@/utils";
import {
  AccountAuthenticator,
  AnyRawTransaction,
  Account,
} from "@aptos-labs/ts-sdk";
import TransactionHash from "~/components/TransactionHash.vue";
import { useToast } from "~/components/ui/toast";
const { toast } = useToast();
const { $walletAdapter } = useNuxtApp();
const { network, connected, account, signTransaction, submitTransaction } =
  $walletAdapter || {};

const APTOS_COIN = "0x1::aptos_coin::AptosCoin";

const transactionToSubmit = ref<AnyRawTransaction>();
const senderAuthenticator = ref<AccountAuthenticator>();
const feepayerAuthenticator = ref<AccountAuthenticator>();

const isSendable = computed(() =>
  isSendableNetwork(connected.value, network.value?.name || undefined),
);

  // create sponsor account
  const SPONSOR_INITIAL_BALANCE = 100_000_000;
  const sponsor = Account.generate();

// Generate a raw transaction using the SDK
const generateTransaction = async (): Promise<AnyRawTransaction> => {
  if (!account.value) {
    throw new Error("no account");
  }
  const transactionToSign = await aptosClient(
    network.value,
  ).transaction.build.simple({
    sender: account.value?.address,
    withFeePayer: true,
    data: {
      function: "0x1::coin::transfer",
      typeArguments: [APTOS_COIN],
      functionArguments: [account.value?.address.toString(), 1], // 1 is in Octas
    },
  });
  return transactionToSign;
};

const onSignTransaction = async () => {
  const transaction = await generateTransaction();
  transactionToSubmit.value = transaction;

  try {
    senderAuthenticator.value = await signTransaction(transaction);
  } catch (error) {
    console.error(error);
  }
};

const onSignTransactionAsSponsor = async () => {
  if (!transactionToSubmit.value) {
    throw new Error("No Transaction to sign");
  }
  try {
    await aptosClient(network.value).fundAccount({
        accountAddress: sponsor.accountAddress,
        amount: SPONSOR_INITIAL_BALANCE,
      });
    feepayerAuthenticator.value = await aptosClient(
        network.value
      ).transaction.signAsFeePayer({
        signer: sponsor,
        transaction: transactionToSubmit.value,
      });
  } catch (error) {
    console.error(error);
  }
};

const onSubmitTransaction = async () => {
  if (!transactionToSubmit.value) {
    throw new Error("No Transaction to sign");
  }
  if (!senderAuthenticator.value) {
    throw new Error("No senderAuthenticator");
  }
  if (!feepayerAuthenticator.value) {
    throw new Error("No feepayerAuthenticator");
  }
  try {
    const response = await submitTransaction({
      transaction: transactionToSubmit.value,
      senderAuthenticator: senderAuthenticator.value,
      feePayerAuthenticator: feepayerAuthenticator.value,
    });
    toast({
      title: "Success",
      description: h(TransactionHash, {
        hash: response.hash,
        network: network.value,
      }),
    });
  } catch (error) {
    console.error(error);
  }
};
</script>

<template>
  <Card>
    <CardHeader>
      <CardTitle>Sponsor Transaction Flow</CardTitle>
    </CardHeader>
    <CardContent class="flex flex-wrap gap-4">
      <Button @click="onSignTransaction" :disabled="!isSendable">
        Sign as sender
      </Button>
      <Button
        @click="onSignTransactionAsSponsor"
        :disabled="!isSendable || !senderAuthenticator"
      >
        Sign as sponsor
      </Button>
      <Button
        @click="onSignTransaction"
        :disabled="!isSendable || !senderAuthenticator"
      >
        Submit transaction
      </Button>
    </CardContent>
  </Card>
</template>
