// apps/nuxt-example/components/TransactonFlows/SingleSigner.vue
<script setup lang="ts">
import { computed, h } from "vue";
import { aptosClient, isSendableNetwork } from "@/utils";
import { AccountAddress, parseTypeTag, U64 } from "@aptos-labs/ts-sdk";
import { InputTransactionData } from "@aptos-labs/wallet-adapter-core";
import TransactionHash from "~/components/TransactionHash.vue";
import { useToast } from "~/components/ui/toast";
const { toast } = useToast();
const { $walletAdapter } = useNuxtApp();
const {
  network,
  connected,
  account,
  signAndSubmitTransaction,
  signMessageAndVerify,
  signMessage,
  signTransaction,
} = $walletAdapter;

const APTOS_COIN = "0x1::aptos_coin::AptosCoin";

const isSendable = computed(() =>
  isSendableNetwork(connected.value, network.value?.name || undefined),
);

const onSignMessageAndVerify = async () => {
  const payload = {
    message: "Hello from Aptos Wallet Adapter",
    nonce: Math.random().toString(16),
  };
  const response = await signMessageAndVerify(payload);
  toast({
    title: "Success",
    description: JSON.stringify({ onSignMessageAndVerify: response }),
  });
};

const onSignMessage = async () => {
  const payload = {
    message: "Hello from Aptos Wallet Adapter",
    nonce: Math.random().toString(16),
  };
  const response = await signMessage(payload);
  toast({
    title: "Success",
    description: JSON.stringify({ onSignMessage: response }),
  });
};

const onSignAndSubmitTransaction = async () => {
  if (!account) return;
  const transaction: InputTransactionData = {
    data: {
      function: "0x1::coin::transfer",
      typeArguments: [APTOS_COIN],
      functionArguments: [account.value?.address, 1], // 1 is in Octas
    },
  };
  try {
    const response = await signAndSubmitTransaction(transaction);
    await aptosClient(network.value).waitForTransaction({
      transactionHash: response.hash,
    });
    toast({
      title: "Success",
      description: h(TransactionHash, {
        hash: response.hash,
        network: network.value,
      }),
    });
  } catch (error) {
    console.error(error);
  }
};

const onSignAndSubmitBCSTransaction = async () => {
  if (!account.value) return;

  try {
    const response = await signAndSubmitTransaction({
      data: {
        function: "0x1::coin::transfer",
        typeArguments: [parseTypeTag(APTOS_COIN)],
        functionArguments: [
          AccountAddress.from(account.value?.address),
          new U64(1),
        ], // 1 is in Octas
      },
    });
    await aptosClient(network.value).waitForTransaction({
      transactionHash: response.hash,
    });
    toast({
      title: "Success",
      description: h(TransactionHash, {
        hash: response.hash,
        network: network.value,
      }),
    });
  } catch (error) {
    console.error(error);
  }
};

// Legacy typescript sdk support
const onSignTransaction = async () => {
  try {
    const payload = {
      type: "entry_function_payload",
      function: "0x1::coin::transfer",
      type_arguments: ["0x1::aptos_coin::AptosCoin"],
      arguments: [account.value?.address, 1], // 1 is in Octas
    };
    const response = await signTransaction(payload);
    toast({
      title: "Success",
      description: JSON.stringify(response),
    });
  } catch (error) {
    console.error(error);
  }
};

const onSignTransactionV2 = async () => {
  if (!account.value) return;

  try {
    const transactionToSign = await aptosClient(
      network.value,
    ).transaction.build.simple({
      sender: account.value?.address,
      data: {
        function: "0x1::coin::transfer",
        typeArguments: [APTOS_COIN],
        functionArguments: [account.value?.address, 1], // 1 is in Octas
      },
    });
    const response = await signTransaction(transactionToSign);
    toast({
      title: "Success",
      description: JSON.stringify(response),
    });
  } catch (error) {
    console.error(error);
  }
};
</script>

<template>
  <Card>
    <CardHeader>
      <CardTitle>Single Signer Flow</CardTitle>
    </CardHeader>
    <CardContent class="flex flex-wrap gap-4">
      <Button @click="onSignAndSubmitTransaction" :disabled="!isSendable">
        Sign and submit transaction
      </Button>
      <Button @click="onSignAndSubmitBCSTransaction" :disabled="!isSendable">
        Sign and submit BCS transaction
      </Button>
      <Button @click="onSignTransaction" :disabled="!isSendable">
        Sign transaction
      </Button>
      <Button @click="onSignTransactionV2" :disabled="!isSendable">
        Sign transaction V2
      </Button>
      <Button @click="onSignMessage" :disabled="!isSendable">
        Sign message
      </Button>
      <Button @click="onSignMessageAndVerify" :disabled="!isSendable">
        Sign message and verify
      </Button>
    </CardContent>
  </Card>
</template>

// apps/nextjs-example/components/transactionFlow/SingleSigner.tsx
import { parseTypeTag, AccountAddress, U64 } from "@aptos-labs/ts-sdk";
import {
  useWallet,
  InputTransactionData,
} from "@aptos-labs/wallet-adapter-react";

import { aptosClient } from "../../utils";
import { useAlert } from "../AlertProvider";
import Button from "../Button";
import Col from "../Col";
import Row from "../Row";
export const APTOS_COIN = "0x1::aptos_coin::AptosCoin";
type SingleSignerTransactionProps = {
  isSendableNetwork: (connected: boolean, network?: string) => boolean;
};

export default function SingleSignerTransaction({
  isSendableNetwork,
}: SingleSignerTransactionProps) {
  const { setSuccessAlertMessage, setSuccessAlertHash } = useAlert();

  const {
    connected,
    account,
    network,
    signAndSubmitTransaction,
    signMessageAndVerify,
    signMessage,
    signTransaction,
  } = useWallet();
  let sendable = isSendableNetwork(connected, network?.name);

  const onSignMessageAndVerify = async () => {
    const payload = {
      message: "Hello from Aptos Wallet Adapter",
      nonce: Math.random().toString(16),
    };
    const response = await signMessageAndVerify(payload);
    setSuccessAlertMessage(
      JSON.stringify({ onSignMessageAndVerify: response })
    );
  };

  const onSignMessage = async () => {
    const payload = {
      message: "Hello from Aptos Wallet Adapter",
      nonce: Math.random().toString(16),
    };
    const response = await signMessage(payload);
    setSuccessAlertMessage(JSON.stringify({ onSignMessage: response }));
  };

  const onSignAndSubmitTransaction = async () => {
    if (!account) return;
    const transaction: InputTransactionData = {
      data: {
        function: "0x1::coin::transfer",
        typeArguments: [APTOS_COIN],
        functionArguments: [account.address, 1], // 1 is in Octas
      },
    };
    try {
      const response = await signAndSubmitTransaction(transaction);
      await aptosClient(network).waitForTransaction({
        transactionHash: response.hash,
      });
      setSuccessAlertHash(response.hash, network);
    } catch (error) {
      console.error(error);
    }
  };

  const onSignAndSubmitBCSTransaction = async () => {
    if (!account) return;

    try {
      const response = await signAndSubmitTransaction({
        data: {
          function: "0x1::coin::transfer",
          typeArguments: [parseTypeTag(APTOS_COIN)],
          functionArguments: [AccountAddress.from(account.address), new U64(1)], // 1 is in Octas
        },
      });
      await aptosClient(network).waitForTransaction({
        transactionHash: response.hash,
      });
      setSuccessAlertHash(response.hash, network);
    } catch (error) {
      console.error(error);
    }
  };

  // Legacy typescript sdk support
  const onSignTransaction = async () => {
    try {
      const payload = {
        type: "entry_function_payload",
        function: "0x1::coin::transfer",
        type_arguments: ["0x1::aptos_coin::AptosCoin"],
        arguments: [account?.address, 1], // 1 is in Octas
      };
      const response = await signTransaction(payload);
      setSuccessAlertMessage(JSON.stringify(response));
    } catch (error) {
      console.error(error);
    }
  };

  const onSignTransactionV2 = async () => {
    if (!account) return;

    try {
      const transactionToSign = await aptosClient(
        network
      ).transaction.build.simple({
        sender: account.address,
        data: {
          function: "0x1::coin::transfer",
          typeArguments: [APTOS_COIN],
          functionArguments: [account.address, 1], // 1 is in Octas
        },
      });
      const response = await signTransaction(transactionToSign);
      setSuccessAlertMessage(JSON.stringify(response));
    } catch (error) {
      console.error(error);
    }
  };

  return (
    <Row>
      <Col title={true} border={true}>
        <h3>Single Signer Flow</h3>
      </Col>
      <Col border={true}>
        <Button
          color={"blue"}
          onClick={onSignAndSubmitTransaction}
          disabled={!sendable}
          message={"Sign and submit transaction"}
        />
        <Button
          color={"blue"}
          onClick={onSignAndSubmitBCSTransaction}
          disabled={!sendable}
          message={"Sign and submit BCS transaction"}
        />
        <Button
          color={"blue"}
          onClick={onSignTransaction}
          disabled={!sendable}
          message={"Sign transaction"}
        />
        <Button
          color={"blue"}
          onClick={onSignTransactionV2}
          disabled={!sendable}
          message={"Sign transaction V2"}
        />

        <Button
          color={"blue"}
          onClick={onSignMessage}
          disabled={!sendable}
          message={"Sign message"}
        />
        <Button
          color={"blue"}
          onClick={onSignMessageAndVerify}
          disabled={!sendable}
          message={"Sign message and verify"}
        />
      </Col>
    </Row>
  );
}
