// apps/nuxt-example/components/TransactonFlows/TransactionParameters.vue
<script setup lang="ts">
import { aptosClient, isSendableNetwork } from "@/utils";
import { InputTransactionData } from "@aptos-labs/wallet-adapter-vue";
const { toast } = useToast();
const { $walletAdapter } = useNuxtApp();
const { network, connected, account, wallet, signAndSubmitTransaction } =
  $walletAdapter || {};

const APTOS_COIN = "0x1::aptos_coin::AptosCoin";
const MaxGasAMount = 10000;

const isSendable = computed(() =>
  isSendableNetwork(connected.value, network.value?.name || undefined),
);

const onSignAndSubmitTransaction = async () => {
  if (!account) return;
  const transaction: InputTransactionData = {
    data: {
      function: "0x1::coin::transfer",
      typeArguments: [APTOS_COIN],
      functionArguments: [account.value?.address, 1], // 1 is in Octas
    },
    options: { maxGasAmount: MaxGasAMount },
  };
  try {
    const commitedTransaction = await signAndSubmitTransaction(transaction);
    const executedTransaction = await aptosClient(
      network.value,
    ).waitForTransaction({
      transactionHash: commitedTransaction.hash,
    });
    // Check maxGasAmount is respected by the current connected Wallet
    if ((executedTransaction as any).max_gas_amount == MaxGasAMount) {
      toast({
        title: "Success",
        description: `${wallet.value?.name ?? "Wallet"} transaction ${executedTransaction.hash} executed with a max gas amount of ${MaxGasAMount}`,
      });
    } else {
      toast({
        variant: "destructive",
        title: "Error",
        description: `${wallet.value?.name ?? "Wallet"} transaction ${executedTransaction.hash} executed with a max gas amount of ${(executedTransaction as any).max_gas_amount}`,
      });
    }
  } catch (error) {
    console.error(error);
  }
};
</script>

<template>
  <Card>
    <CardHeader>
      <CardTitle> Validate Transaction Parameters </CardTitle>
    </CardHeader>
    <CardContent class="flex flex-wrap gap-4">
      <Button @click="onSignAndSubmitTransaction" :disabled="!isSendable">
        With MaxGasAmount
      </Button>
    </CardContent>
  </Card>
</template>

// apps/nextjs-example/components/transactionFlow/TransactionParameters.tsx
import {
  useWallet,
  InputTransactionData,
} from "@aptos-labs/wallet-adapter-react";

import { aptosClient } from "../../utils";
import { useAlert } from "../AlertProvider";
import Button from "../Button";
import Col from "../Col";
import Row from "../Row";
export const APTOS_COIN = "0x1::aptos_coin::AptosCoin";
const MaxGasAMount = 10000;
type SingleSignerTransactionProps = {
  isSendableNetwork: (connected: boolean, network?: string) => boolean;
};

export default function TransactionParameters({
  isSendableNetwork,
}: SingleSignerTransactionProps) {
  const { setSuccessAlertMessage, setErrorAlertMessage } = useAlert();

  const { connected, account, network, signAndSubmitTransaction, wallet } =
    useWallet();
  let sendable = isSendableNetwork(connected, network?.name);

  const onSignAndSubmitTransaction = async () => {
    if (!account) return;
    const transaction: InputTransactionData = {
      data: {
        function: "0x1::coin::transfer",
        typeArguments: [APTOS_COIN],
        functionArguments: [account.address, 1], // 1 is in Octas
      },
      options: { maxGasAmount: MaxGasAMount },
    };
    try {
      const commitedTransaction = await signAndSubmitTransaction(transaction);
      const executedTransaction = await aptosClient(network).waitForTransaction(
        {
          transactionHash: commitedTransaction.hash,
        }
      );
      // Check maxGasAmount is respected by the current connected Wallet
      if ((executedTransaction as any).max_gas_amount == MaxGasAMount) {
        setSuccessAlertMessage(
          `${wallet?.name} transaction ${executedTransaction.hash} executed with a max gas amount of ${MaxGasAMount}`
        );
      } else {
        setErrorAlertMessage(
          `${wallet?.name} transaction ${executedTransaction.hash} executed with a max gas amount of ${(executedTransaction as any).max_gas_amount}`
        );
      }
    } catch (error) {
      console.error(error);
    }
  };

  return (
    <Row>
      <Col title={true} border={true}>
        <h3>Validate Transaction Parameters</h3>
      </Col>
      <Col border={true}>
        <Button
          color={"blue"}
          onClick={onSignAndSubmitTransaction}
          disabled={!sendable}
          message={"With MaxGasAmount"}
        />
      </Col>
    </Row>
  );
}
